// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChat(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateChat'](arg1, arg2, arg3);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function SendConfirmation(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendConfirmation'](arg1, arg2, arg3);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function Signup(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['Signup'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function StreamMessage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StreamMessage'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateChat'](arg1, arg2, arg3, arg4);
}

export function UpdateUser(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2, arg3, arg4, arg5);
}
