// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChat(arg1:number,arg2:string,arg3:string):Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:string,arg2:string,arg3:string):Promise<number>;

export function SendConfirmation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendMessage(arg1:string):Promise<string>;

export function Signup(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<number>;

export function StreamMessage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function UpdateChat(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateUser(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
