// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function SendConfirmation(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SendMessage(arg1:string):Promise<string>;

export function StreamMessage(arg1:string,arg2:string,arg3:string):Promise<void>;
